### ISSUE TITLE
Is it bidirectional the QLSTM implementation?

### ISSUE THREAD

**Issue by wellescastro** [Orkis-Research/Pytorch-Quaternion-Neural-Networks#2]
Hi!

I'm just wondering if the LSTM code in this repo is bidirectional since I didn't find any bidirectional flag, maybe is just the default behaviour.

Thank you,

Dayvid.

**Comment by TParcollet** [comment]
Hey ! No it is not, I will make the change very soon. Until then, you can take a look at the file neural_networks.py on the PyTorch-Kaldi repository, since my LSTMs are inspired by this file.

**Comment by wellescastro** [comment]
Okay! Thank you, I'm gonna take a look :)
